### ISSUE TITLE
javascript error: "Uncaught TypeError: $(...).iconList is not a function

### ISSUE THREAD

**Issue by jeffreykemp** [grlicaa/IconPicker#2]
Changed a text field to use the IconPicker plugin. On clicking the list icon the javascript console shows the following error:

    IPdoc.js:45 Uncaught TypeError: $(...).iconList is not a function
        at HTMLUListElement.<anonymous> (IPdoc.js:45)
        at Function.each (desktop_all.min.js?v=19.1.0.00.15:2)
        at w.fn.init.each (desktop_all.min.js?v=19.1.0.00.15:2)
        at addItemList (IPdoc.js:44)
        at IPdoc.js:441

The list does then show and the icons can be viewed and selected.

Oracle Application Express 19.1.0.00.15

**Comment by grlicaa** [comment]
Hi Jeffrey,

first of all thanks for your feedback. I saw same error few times, it depends on opening page, normal/modal. Didn't have time to solve it, so I put addition option to disable "iconList". (workaround forr now)
shared components -> Component settings (1)
![UseWidgetIconList](https://user-images.githubusercontent.com/30799807/57212117-ee21df00-6fe2-11e9-9c99-49a51a2ab632.png)

I'll put some more work into this plug-in in next few weeks, I also have few additional bugs to solve :)

Best regards,
Andrej
