### ISSUE TITLE
Label is corrupted when the template type is Floating 

### ISSUE THREAD

**Issue by madmexx2002** [grlicaa/IconPicker#3]
Hello Andrej

Very nice Plugin and a function i really missed for a long time! Thank you. Now my users can select custom icons everywhere.

When the template type for the item is set to floating the label doesn't move over the selected icon name.  As u can see on the picture below. 

![image](https://user-images.githubusercontent.com/36326420/126078017-0154ca80-8be3-4dda-a9e7-504aa7fe8d76.png)

I had the same issue a few days ago with a Popup LOV wich was set by javascript. My solution also works for this issue. After setting the value the container element need the class ` js-show-label`. 

![image](https://user-images.githubusercontent.com/36326420/126077976-08d75087-70db-4f5c-8515-897d2e9e5678.png)

Best regards Mark

**Comment by grlicaa** [comment]
Hi Mark,

even I think this is more an APEX theme flaw than a plugin, I'll add it to the list for the next release (not sure when).

Thank you for the suggestion!


Kind regards, Andrej

**Comment by grlicaa** [comment]
Finally fixed and closed! 
Thank you again for reporting this!
